services:
  postgres:
    image: postgres:16-alpine
    container_name: linkvault_postgres
    environment:
      POSTGRES_DB: linkvault
      POSTGRES_USER: linkvault
      POSTGRES_PASSWORD: linkvault
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U linkvault -d linkvault"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: linkvault_api
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgres://linkvault:linkvault@postgres:5432/linkvault
      CORS_ORIGIN: http://localhost:5173
      JWT_SECRET: change-me-dev
      JWT_REFRESH_SECRET: change-me-dev-refresh
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        VITE_API_URL: http://localhost:3000
    container_name: linkvault_web
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  postgres_data:


