[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = [
  "corepack enable",
  "corepack prepare pnpm@latest --activate",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
  "pnpm --filter @linkvault/shared build",
  "pnpm --filter api build"
]

[start]
cmd = "sh -c 'node apps/api/dist/db/migrate.js && node apps/api/dist/index.js'"
